[package]
name = "hyprstream"
version = "0.1.0"
edition = "2021"
description = "High-performance metrics storage and query service using Arrow Flight SQL"
documentation = "https://docs.rs/hyprstream"
readme = "README.md"

[lib]
name = "hyprstream_core"
path = "src/lib.rs"
doctest = true

[[bin]]
name = "hyprstream"
path = "src/bin/main.rs"
doc = true

[dependencies]
arrow = "54.0.0"
arrow-flight = { version = "54.0.0", features = ["cli", "flight-sql-experimental", "tls", "tokio"] }
bytes = "1.9.0"
duckdb = { version = "1.1.1", features = ["bundled"] }
futures = { version = "0.3.31", features = ["alloc"] }
polars = "0.45.1"
tokio = { version = "1.42.0", features = ["macros", "rt", "rt-multi-thread"] }
tokio-rustls = "0.26.1"
tonic = { version = "0.12.3", features = ["transport", "codegen", "prost"] }
async-trait = "0.1"
sqlparser = "0.39.0"
adbc_core = { version = "0.15.0", features = ["driver_manager"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
lazy_static = "1.4"
serde_json = "1.0"

# ADBC dependencies
arrow-array = "54.0.0"
arrow-schema = "54.0.0"
arrow-ipc = "54.0.0"

# Configuration
config = { version = "0.13", features = ["toml"] }
clap = { version = "4.4", features = ["derive", "env"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bincode = "1.3.3"
tokio-stream = "0.1.17"
hex = "0.4"
chrono = "0.4"
